#!/usr/bin/env php
<?php
if (is_file(__DIR__ . '/../vendor/autoload.php')) {
    require __DIR__ . '/../vendor/autoload.php';
} else if (is_file(__DIR__ . '/../../../autoload.php')) {
    require __DIR__ . '/../../../autoload.php';
}

$commander = new Commander();
$commander->name('assets')
    ->version('0.1.0')
    ->command(
        array(
            'name' => 'clean',
            'description' => 'Remove old compiled assets',
            'arguments' => array(
                array(
                    'name' => 'config',
                    'description' => 'Path of the config file'
                )
            ),
            'callback' => function($input, $output) {
                \Assets\Console::clean($input);
            }
        )
    )
    ->command(
        array(
            'name' => 'precompile',
            'description' => 'Compile all the assets named in $config["precompile"]["files"]',
            'arguments' => array(
                array(
                    'name' => 'config',
                    'description' => 'Path of the config file'
                )
            ),
            'callback' => function($input, $output) {
                \Assets\Console::precompile($input, $output);
            }
        )
    )
    ->run();